import docx
from docx.shared import Pt
FONT='Times New Roman'
d=docx.Document(); d.styles['Normal'].font.name=FONT; d.styles['Normal'].font.size=Pt(12)
def title(t):
    p=d.add_paragraph(); r=p.add_run(t); r.bold=True; r.font.name=FONT; r.font.size=Pt(14)
def sub(t):
    p=d.add_paragraph(); r=p.add_run(t); r.bold=True; r.italic=True; r.font.name=FONT; r.font.size=Pt(12)
def para(t):
    p=d.add_paragraph(); p.paragraph_format.line_spacing=2.0; r=p.add_run(t); r.font.name=FONT; r.font.size=Pt(12)

title('Methods')
para('This study was reported in accordance with the Transparent Reporting of a multivariable prediction model for Individual Prognosis Or Diagnosis statement for artificial intelligence and machine learning (TRIPOD+AI; Collins et al., BMJ 2024), and the risk of bias was self-assessed using the Prediction model Risk Of Bias ASsessment Tool (PROBAST; Moons and Wolff et al., Ann Intern Med 2019). The analysis followed a prespecified plan, and all code is publicly available to permit independent reproduction.')

sub('Data sources')
para('The model was developed using the Medical Information Mart for Intensive Care, version IV (MIMIC-IV v3.1; Johnson et al., Sci Data 2023), a single-centre critical care database from the Beth Israel Deaconess Medical Center spanning 2008 to 2019. External validation was performed in the eICU Collaborative Research Database (Pollard et al., Sci Data 2018), a multicentre database comprising intensive care admissions from 208 hospitals across the United States during 2014 and 2015. Both databases are deidentified and accessed under PhysioNet credentialed data use agreements. The use of these databases for the present analysis required no additional institutional review board approval beyond the credentialing process.')

sub('Study population')
para('Adult patients with cardiogenic shock were identified in MIMIC-IV using a documentation-anchored phenotype. A cardiogenic shock admission was defined by the presence of a corresponding International Classification of Diseases code (ICD-10 R57.0 or ICD-9 785.51) or an affirmative mention of cardiogenic shock in the discharge summary, together with at least one objective criterion of shock recorded within the first 24 hours of intensive care, namely a systolic blood pressure below 90 mmHg or a mean arterial pressure below 65 mmHg, an arterial lactate of at least 2 mmol/L, or the administration of a vasoactive or inotropic agent or mechanical circulatory support. Discharge summaries were classified using a context-aware natural language pipeline based on the ConText algorithm, which distinguishes affirmed mentions from negated, historical, hypothetical, and uncertain contexts. The classifier was validated against manual review of affirmed mentions, with a note-level positive predictive value of 96.5 percent. One index intensive care admission was retained per patient. No minimum length of stay was imposed, so that early deaths were retained and immortal time bias was avoided.')
para('The choice of an all-unit, documentation-anchored cohort was deliberate. Restricting to the coronary care unit, as in the predecessor model, excluded the majority of cardiogenic shock admissions, including the mechanical circulatory support population managed in the cardiac surgical unit, and a loosely defined phenotype admitted patients without genuine cardiogenic shock and inflated the apparent missingness of perfusion markers.')
para('The external validation cohort comprised eICU admissions with an Acute Physiology and Chronic Health Evaluation diagnosis string indicating cardiogenic shock. This phenotype is broader than the development definition, and the difference was retained intentionally to provide an honest test of transportability rather than a curated match; a harmonized cohort additionally requiring at least one objective criterion was examined as a sensitivity analysis.')

sub('Outcomes')
para('The primary outcome was in-hospital mortality. The secondary outcome was 30-day mortality. In-hospital mortality was selected as the primary endpoint because it reflects the acute phase during which the score is intended to inform escalation and goals-of-care decisions, and because in this cohort 87.8 percent of 30-day deaths occurred during the index hospitalization, indicating close concordance between the two endpoints.')

sub('Predictors')
para('Candidate predictors were extracted as the most recent value recorded up to the 24-hour reference time, rather than the worst value, so that the score reflects the current physiological state and can improve as the patient improves (Steyerberg, Clinical Prediction Models, 2019). All measurements were restricted to charttimes at or before the reference time to preclude the use of future information. The final model comprised six variables, namely arterial lactate, urine output rate, out-of-hospital cardiac arrest, age, blood urea nitrogen, and red cell distribution width. The urine output rate was calculated as the first-day urine volume normalized by body weight and by the actual number of observed hours, capped at 24, to avoid underestimating the rate in patients with brief stays. For the externally deployable formulation, the anion gap was substituted for lactate where lactate was unavailable, and the anion gap was computed identically in both databases from serum sodium, chloride, and bicarbonate (Kraut and Madias, Clin J Am Soc Nephrol 2007) rather than taken from the institution-specific laboratory field, so that the categorical thresholds transported between databases.')

sub('Missing data')
para('Both perfusion variables were missing not at random, in opposite directions: patients without a recorded lactate had lower mortality, reflecting more selective ordering, whereas patients without a recorded urine output rate had higher mortality. The deployed model retained the six physiological variables without missingness indicators, with median imputation serving as the explicit point-of-care rule and the harmonized anion gap as a prespecified substitution for missing lactate, an approach that provides a real-world scoring rule for incomplete data. Discrimination and calibration were reported separately for patients with and without a measured lactate, and multiple imputation by chained equations was examined as a sensitivity analysis.')

sub('Model development')
para('The modelling algorithm was selected through a comparison of penalized logistic regression, random forests, and gradient boosting on a common feature pool. Discrimination was equivalent across algorithms while the machine learning models were materially miscalibrated, consistent with the broader evidence that flexible machine learning offers no discrimination advantage over logistic regression for clinical prediction with structured data (Christodoulou et al., J Clin Epidemiol 2019). Penalized logistic regression was therefore adopted. Predictors were selected by bootstrap stability selection from a broad clinical pool, after which features that were treatment-dependent, computed from other variables, proximal to the outcome, or themselves composite severity scores were removed by prespecified clinical rules. The six retained variables were selected in every bootstrap resample. The available sample comprised 1,188 outcome events for six predictor parameters, corresponding to approximately 198 events per parameter, well above accepted minimums for model development (Riley et al., Stat Med 2019). Continuous predictors were winsorized at the first and 99th percentiles and standardized. A bedside integer score was derived by the method of Sullivan and colleagues (Stat Med 2004), in which each variable is categorized, an ordinal logistic model is fit, and the coefficients are scaled and rounded to integer points; categorical thresholds were anchored to established clinical cut-points where they existed and to the observed dose-response otherwise, and the integer discrimination was confirmed to be robust across alternative threshold schemes.')

sub('Validation')
para('Internal validity was assessed by bootstrap optimism correction with 500 resamples, in which the integer points were re-derived within each resample, and by five-fold cross-validation. A single split-sample approach was deliberately avoided as statistically inefficient for a cohort of this size. For external validation, the entire pipeline, comprising the winsorization bounds, imputation values, standardization parameters, and model coefficients, was frozen on the development data and applied without modification to the eICU cohort. Discrimination was summarized by the area under the receiver operating characteristic curve with bootstrap confidence intervals, and calibration by the calibration slope, calibration-in-the-large, a flexible loess calibration curve, and the Brier score (Van Calster et al.). Clinical utility was assessed by decision curve analysis (Vickers and Elkin, Med Decis Making 2006). Logistic recalibration of the external predictions was reported to support the presentation of risk categories as relative strata.')

sub('Comparator scores and SCAI staging')
para('CS-MORT-6 was compared against the externally computable echo-free score of Yamga and colleagues (J Am Heart Assoc 2023) and against the original eight-variable predecessor, with differences in discrimination tested using the method of DeLong and colleagues (Biometrics 1988). The CardShock score and the IABP-SHOCK II score could not be evaluated externally because their defining inputs, left ventricular ejection fraction and post-procedural coronary flow grade, are not available in eICU. The Society for Cardiovascular Angiography and Interventions shock stage (Naidu et al., J Am Coll Cardiol 2022) was operationalized using a drug, device, and arrest escalation hierarchy, and the ability of CS-MORT-6 to stratify mortality within each stage was assessed by computing the score across risk tertiles within stages.')

sub('Dynamic, sensitivity, fairness, and heterogeneity analyses')
para('To evaluate serial use, the frozen integer score was recomputed at 24 and 48 hours using the most recent values available at each time, and the association between the change in score and subsequent mortality was assessed among patients alive at 48 hours, with this landmark conditioning stated explicitly. Prespecified sensitivity analyses examined the cohort restricted to code-confirmed cardiogenic shock, the cohort excluding patients meeting Sepsis-3 criteria (Singer et al., JAMA 2016), the cohort excluding patients with a culture-confirmed infection, the cohort excluding patients transitioned to comfort-focused care, a model excluding out-of-hospital cardiac arrest, complete-case analysis, and multiple imputation. Because Sepsis-3 is non-specific in cardiogenic shock, where the organ-dysfunction criterion is met through hypoperfusion and the suspicion-of-infection criterion is met through the routine empiric work-up, a culture-confirmed definition of mixed shock was examined as the more specific phenotype. Subgroup performance was reported by sex and by race to assess fairness, and heterogeneity in performance across eICU hospitals was quantified.')

sub('Statistical software and reproducibility')
para('Analyses were performed in Python using the scikit-learn library, and publication figures were generated in R. A fixed random seed was used throughout. The complete code and the prespecified analysis plan are publicly available, and the databases are obtainable through PhysioNet under the credentialed data use agreement.')

d.save('manuscript/DRAFT_Methods.docx'); print('wrote manuscript/DRAFT_Methods.docx')
import docx as _d
chk=_d.Document('manuscript/DRAFT_Methods.docx'); print('paras:',len([p for p in chk.paragraphs if p.text.strip()]),'| font:',chk.styles['Normal'].font.name,int(chk.styles['Normal'].font.size.pt),'pt')
